### ISSUE TITLE
Readability 

### ISSUE THREAD

**Issue by Torizoa** [dwbrite/ajitvpai.com#12]
Transitioning from sections "What does all of this mean?" (Dark Background) to "Potential problems..." (light background) is killer on the eyes.

**Comment by adamellsworth** [comment]
Furthermore, there seems to be quite a few contradictions in the literature. Take the first paragraph for instance:

> We can't say we know exactly, but it appears that his intentions might be to make more money for existing ISPs that control the United States. We do know, however, that most of the arguments against Net Neutrality revolve around money. 

First, we _'cant say we know'_ why money is involved on Pai's behalf, then _'we do know'_ that it is being funneled. Both are provided without any sources. 

How do we know what we do and don't know? As banal and epistemological as this this kind of inquiry is, it absolutely needs sources to back it up if it is to hold its ground.
