### ISSUE TITLE
List examples that have already happened

### ISSUE THREAD

**Issue by crosma** [dwbrite/ajitvpai.com#15]
There have been many examples where ISPs have violated net neutrality such as throttling Netflix. This website should list and cite them.

**Comment by dwbrite** [comment]
They are there - although I'm not sure that they're in the right place. I'll look into it tomorrow morning.

**Comment by crosma** [comment]
Ah, I see it now. Sorry, too tired for this.

**Comment by crosma** [comment]
Ah, I see it now. Sorry, too tired for this.
