### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by adamellsworth** [dwbrite/ajitvpai.com#21]
I am not cognizant of what the legal issues are in using somebody's name as a domain without their consent.

Could someone else chime in on this?

**Comment by dwbrite** [comment]
This reddit thread talks about it: 
https://www.reddit.com/r/bestof/comments/6dc7cg/uhdmoney_buys_the_chairman_of_the_fccs_domain_and/di1qbjl/

Seems like it should be fine.
