### ISSUE TITLE
List of Political persons in opposition to NN

### ISSUE THREAD

**Issue by adamellsworth** [dwbrite/ajitvpai.com#22]
Would the article do well to get a complete list of those Reps. in collusion with ISPs against NN?

__If so:__

What House or Senate reps are against NN at both State and Federal Levels?

What House or Senate members accepted large donations from ISPs, in what denominations were those donations given, and from which ISPs or representatives of those companies were they from?

What kind of automation can we use to scrape this information (as opposed to crowdsourcing it)?

Furthermore, would this kind of information require a second route other than `/`?

**Comment by indiandennis** [comment]
https://www.opensecrets.org/ has lots of data on politicians and industry contributions/lobbying. If you want a more direct list, [this article from The Verge](https://www.theverge.com/2017/3/29/15100620/congress-fcc-isp-web-browsing-privacy-fire-sale) has a table with the data. 
[Show me the money](https://www.followthemoney.org/show-me?law-ot=L,U&d-cci=24#[{1|gro=y,law-eid,law-did,d-cci,law-p) also has a lot of data and a JSON API, but it is a little difficult to navigate the site at first.
