### ISSUE TITLE
"What can I do?" section

### ISSUE THREAD

**Issue by adamellsworth** [dwbrite/ajitvpai.com#24]
Sending comments to the FCC has, in the past two weeks, proven to be an unreliable way to voice an opinion to the Commission.

We would do well to provide template pages such as Mozilla's https://dearfcc.org/ which do not force a single opinion but does allow a forum wherein an individual can send their own thoughts on the issue (_for_ or _against_) to their state representatives. 

State House rulings have significant weight in getting items to the Congressional level.

**Comment by davecan** [comment]
Good strategy. States are also starting to move forward with their own regulations of ISPs. Ten states announced legislation to block them from selling individual usage history: http://www.govtech.com/policy/10-States-Take-Internet-Privacy-Matters-Into-Their-Own-Hands.html
