### ISSUE TITLE
Issue #13 closed, but not resolved.

### ISSUE THREAD

**Issue by NolanSyKinsley** [dwbrite/ajitvpai.com#25]
That section alone is still having issues with punctuation as seen here: http://i.imgur.com/SBwGBYd.png

On Linux, Google Chrome version 58.0.3029.110. May be an issue with Chrome's auto encoding as the page is UTF-8, but Chrome no longer allows manually setting encoding, and does auto encoding.

**Comment by dwbrite** [comment]
Clear your cache.

**Comment by NolanSyKinsley** [comment]
Tried, chrome won't let me go back now due to invalid security credentials. http://i.imgur.com/5ux3yh4.png

**Comment by dwbrite** [comment]
See #26 (includes fix)

**Comment by NolanSyKinsley** [comment]
Negative, followed all instructions, cleared all browsing data, all cookies, no results, the image I provided is still the same result. This is nothing to do with my cache, or my system. At this point, as the image above shows, there is something wrong with the name of the cert that chrome is unhappy with.
