### ISSUE TITLE
HTTPS Cert no longer valid (ERR_CERT_COMMON_NAME_INVALID)

### ISSUE THREAD

**Issue by adamellsworth** [dwbrite/ajitvpai.com#26]
Not sure which cert service you're using, but https://letsencrypt.org/ provides free and valid certs.

![screen shot 2017-05-25 at 11 29 56 pm](https://cloud.githubusercontent.com/assets/7034617/26483477/1574d592-41a2-11e7-86c1-011e41bb5b69.png)

**Comment by dwbrite** [comment]
The SSL enabled site has been disabled temporarily. It will be back up in the morning.

If you're having trouble reaching http://ajitvpai.com, be sure to clear both cache and "site preferences".

**Comment by dwbrite** [comment]
Switched the domain back to the VPS. Turns out the cron job for git pulls wasn't working. Everything should be fine now.
