### ISSUE TITLE
Decrease size of Comcast and Verizon logos

### ISSUE THREAD

**Issue by vanshg** [dwbrite/ajitvpai.com#27]
When I first opened the website, my first thought was that it was an advertisement for Comcast/Verizon and immediately wanted to close the page. 

Maybe decreasing the size of the logos, and increasing the font size of "Ruining the Internet as we know it" would be better

**Comment by MrBenJ** [comment]
@vanshg - there were some recent updates to the site. Can you test this on your own on a mobile and desktop browser and let me know if this is still an issue? Assigning to you. If it's to your satisfaction, please close this issue. Thank you!
