### ISSUE TITLE
Enforce SSL

### ISSUE THREAD

**Issue by tylerchilds** [dwbrite/ajitvpai.com#3]
I think by making the URL in the address bar always display as https just carries extra credibility for the content on the site. I've used CloudFlare in the past to do this with GitHub Pages. The steps in this link should work.

https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by dwbrite** [comment]
Looks like it's not truly secure, but I'll look into it. It might be a good temporary solution and at least give the illusion of security.

**Comment by SunsparcSolaris** [comment]
@tylerchilds @dwbrite and I are setting everything up on a VPS, SSL will be forced once that is done.
