### ISSUE TITLE
Keep getting errors..

### ISSUE THREAD

**Issue by cluu79** [dwbrite/ajitvpai.com#30]
How do I add my commits?
I keep getting "unable to access https://github.com/dwbrite/ajitvpai.com.git requested URL returned error: 403.

What do I need to do?

**Comment by SunsparcSolaris** [comment]
How are you attempting to commit?

**Comment by cluu79** [comment]
i cloned the repo and made changes and push tried to push my commits.

Admittedly, i'm new to this, but i want to contribute.

If you have any ideas, let me know.

**Comment by dwbrite** [comment]
I found this:
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed#7771927

Are you logged in when you push? (Assuming you're running from the terminal)

**Comment by MrBenJ** [comment]
Hey @cluu79 - If you haven't been added as a contributor, you'll need to fork the repo
instead of clone. Commit your changes to your forked repo and then open a
pull request.

You picked a great project to contribute to :). I'll be doing the same in a
little bit too, since I want to help out as well!

**Comment by cluu79** [comment]
Thank you Mr. Ben, 
i had to fork it.

everything works well now.
Thanks

**Comment by MrBenJ** [comment]
You're welcome @cluu79 ! Even if you're a beginner, it makes me happy that you want to contribute to something like this. Everyone's affected by this, so let's all make it happen!

@dwbrite  - Can you close this issue or mark resolved? Thank you!

**Comment by cluu79** [comment]
Thank you sir.
