### ISSUE TITLE
"WHAT IS TITLE II?" in red background sets an unfriendly tone

### ISSUE THREAD

**Issue by sqz** [dwbrite/ajitvpai.com#36]
This is a really well-designed website already, with great use of space, font clarity, only important high impact images and short text points.

The use of grey background for "POTENTIAL PROBLEMS" and potential outcomes is genius.

However, I would recommend you are careful how you use large swathes of the color red. This always has a warning, high impact or even adversarial tone.

So, perhaps for example remove the total red background from the "friendly"-toned "WHAT IS TITLE II?" and make that blue background like "WHAT IS NET NEUTRALITY" or white background.

This would leave the critical consequences of ignoring or supporting anti-net neutrality in the only big red block: "WHAT DOES ALL OF THIS MEAN?"

**Comment by dwbrite** [comment]
Reorganized and recolored
