### ISSUE TITLE
Masthead image pushes "Ruining the Internet..." below the fold

### ISSUE THREAD

**Issue by davecan** [dwbrite/ajitvpai.com#37]
I'm running at 1920x1080 resolution and the masthead image flows off the bottom of the screen. The emotional tagline "Ruining the Internet as we know it" isn't visible above the fold. Recommend cropping the top image a bit. Not sure how it looks at all other resolutions, though a quick test with the Chrome dev tools shows it above the fold in at least a few other resolutions.

Screenshot:  https://imgur.com/a/KdCzt

**Comment by dwbrite** [comment]
This is fixed, just waiting on the server to update
