### ISSUE TITLE
See why at&t  already planned for a "closed" net.

### ISSUE THREAD

**Issue by CurtisJNeeleyJr** [dwbrite/ajitvpai.com#42]
https://www.att.com/support/internet/usage.html

## AT&T Internet plans

You will receive an email notice the first time your usage exceeds the monthly data allowance. In subsequent months we will continue to send you alerts if your usage approaches or exceeds the amount of data included in your plan. If you exceed your monthly data plan a third time (bill cycle), and as our agreement provides, we’ll charge you $10 for each additional 50GB of data provided to you that month. The maximum overage charge is $100 a month for AT&T Internet and $200 a month for DSL and Fixed Wireless Internet.

A $30 unlimited data allowance is also available for AT&T Internet customers to purchase as an optional feature of your Internet service. Or if you purchase DIRECTV or U-verse TV service with your Internet service on a combined bill, you will receive an unlimited usage allowance. That’s a $30 value at no additional charge as part of the discount. This is only available for AT&T Internet, not DSL or Fixed Wireless Internet.

**Comment by nugget** [comment]
I am confused by this.  The issue does not seem actionable.  What content are you suggesting and in what context?

**Comment by CurtisJNeeleyJr** [comment]
This is discrimatory billing for similar data being announced for DirectTV versus Netflix or other. 
Netflix, et. al. have standing today to stop this unfair type billing in District Court as a class-action.

**Comment by CurtisJNeeleyJr** [comment]
This is the type differential billing Interim Chairman Pai is calling ISPs giving away "free-stuff".
