### ISSUE TITLE
Let's use more "clickbaity" content

### ISSUE THREAD

**Issue by JPaulMora** [dwbrite/ajitvpai.com#44]
I'm reffering to a suggestion someone made to replace "save net neutrality" with "stop ISPs from blocking Netflix". 

When we talk about net neutrality as a general term you need to explain a little before it becomes relevant to the average reader, instead let's part from a specific _relevant_ example and generalize over it.

Eg. "Without Title 2 you could be charged extra to watch Netflix, even worse, ISPs can legally block Netflix effectively forcing you to pay for X other service of their own.. no matter how crappy it is.

This also applies to any other site you may want to visit! Even this one could be blocked if they wanted to, which means they could block news and information they conveniently don't want you to see, or any other service that they don't want you to use (Google wallet example)."

**Comment by MrBenJ** [comment]
Closing this issue because of disinterest from community
